# Generated by Django 4.1.7 on 2023-02-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_customer_created_at_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='test_decimal',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='test_float',
            field=models.FloatField(null=True),
        ),
    ]
