# Generated by Django 4.1.7 on 2023-02-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customer_status_customer_test_decimal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('unallowed', 'Unallowed')], max_length=30, null=True),
        ),
    ]
